#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

export BASHRC_FILES="$XDG_CONFIG_HOME/bashrc.d"
export RC_FILES="$XDG_CONFIG_HOME/rc_files"

source "$BASHRC_FILES/shopt.sh"
source "$BASHRC_FILES/completion.sh"

for file in "$RC_FILES"/*.sh; do
    # shellcheck source=/dev/null
    source "$file"
done

# set variable identifying the chroot you work in (used in the prompt below)
if [[ -z "${debian_chroot:-}" ]] && [[ -r /etc/debian_chroot ]]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
