# ────────────────────────────────────────────────────────────
# Omarchy Matte Black Theme for Alacritty
# By tahayvr
# https://github.com/tahayvr
# ────────────────────────────────────────────────────────────

[colors]
[colors.primary]
background = "#121212"
foreground = "#bebebe"
dim_foreground = "#8a8a8d"

[colors.cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.selection]
text = "CellForeground"
background = "#333333"

[colors.normal]
black = "#3B4252"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#88C0D0"
white = "#E5E9F0"

[colors.bright]
black = "#4C566A"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#ECEFF4"
