$active=~/images/wallpapers/matte-black/1-matte-black.jpg

preload = $active
wallpaper {
  # Default entry
  monitor =
  path = $active
}

# enable rendering of the hyprland splash over the wallpaper
# default: true
splash = true

# how far up should the splash be displayed
# default: 20 (pixels?)
splash_offset = 40

# how opaque the splash is
# default: 0.8
# splash_opacity = 55FFFFFF

# whether to enable IPC
# default: true
ipc = true
