$active=/home/s1lv3r/images/wallpapers/matte-black/1-matte-black.jpg

preload = $active
wallpaper = , $active

# Enable the hyprland splash text
# default: false
splash = true

# How far in % from the bottom of the screen the splash should be put
# default: 2.0
#splash_offset = 2.0

# What color the splash text should be in AARRGGBB format
# default: 55FFFFFF
# splash_color = 55FFFFFF

# If the IPC socket should be enabled through hyprctl
# default: true
ipc = true
