monitorv2 {
  output = eDP-1
  mode = 2880x1920@120
  position = 0x1080
  scale = 1.5
  transform = 0
  vrr = true
}

monitorv2 {
    output = DP-4
    mode = 1920x1080@60
    position = 0x0
}

monitorv2 {
    output = DP-3
    mode = 1920x1080@60
    position = 0x0
}
