#!/usr/bin/env zsh
# vi: ft=sh
# shellcheck shell=bash disable=SC1091

#zmodload zsh/zprof

zmodload zsh/complist
autoload -U compinit && compinit -d ~/.cache/zcompdump
autoload -U bashcompinit && bashcompinit -d ~/.cache/zbashcompdump
autoload -U add-zsh-hook

export SCRIPTS_DIR="$HOME/.config/zsh"
export ZSH_SCRIPTS=$SCRIPTS_DIR/zshrc
export RC_FILES="$XDG_CONFIG_HOME/rc_files"

# shellcheck disable=SC2206
# We cant quote, it breaks zsh _hard_
export fpath=("${SCRIPTS_DIR}/completions" $fpath)

if [[ "$TERM" == "linux" ]]; then
    # shellcheck source=zshrc/basic-prompt.zsh
    source "$SCRIPTS_DIR/zshrc/basic-prompt.zsh"
else
    # shellcheck source=p10k.init.zsh
    source "$SCRIPTS_DIR/p10k.init.zsh"
fi

# shellcheck source=zsh-autocomplete.zsh
source "$SCRIPTS_DIR/zsh-autocomplete.zsh"
source "$ZSH_SCRIPTS/options.zsh"     # Options using setopt
source "$ZSH_SCRIPTS/keybinds.zsh"          # Shell keybinds
source "$ZSH_SCRIPTS/completion.zsh"        # Completion scripts

for file in "$RC_FILES"/*.sh; do
    # shellcheck source=/dev/null
    source "$file"
done

unset ZSH_SCRIPTS RC_FILES

# Zi options
declare -A ZI

ZI[HOME_DIR]="$HOME/.local/share/zi"
ZI[BIN_DIR]="${ZI[HOME_DIR]}/bin"

source "${ZI[HOME_DIR]}/bin/zi.zsh"
autoload -Uz _zi
(( ${+_comps} )) && _comps["zi"]=_zi

# P10K theme
zi ice if"[ ${TERM##*-} = '256color' ] || [ ${terminfo[colors]:?} -gt 255 ]" depth=1
zi light romkatv/powerlevel10k

# Various other stuff
zi load zsh-users/zsh-syntax-highlighting
zi load zsh-users/zsh-autosuggestions
zi load zsh-users/zsh-completions

omz_plugins=(
    pip
    aws
    node
    git
    command-not-found
    docker
    docker-compose
    gitignore
    aliases
    archlinux
)

for plugin in "${omz_plugins[@]}"; do
    zi snippet "OMZP::${plugin}"
done

zi light-mode for z-shell/z-a-meta-plugins @annexes

zicompinit
