# PacketTracer WindowsRule
# Global for PacketTracer


### Appearance ###
#windowrulev2 = noanim on,class:^(PacketTracer)$
#windowrulev2 = noblur on,class:^(PacketTracer)$
#windowrulev2 = nodim on,class:^(PacketTracer)$
#windowrulev2 = noshadow on,class:^(PacketTracer)$
#windowrulev2 = opaque on,class:^(PacketTracer)$
#windowrulev2 = bordersize 0,class:^(PacketTracer)$
#windowrulev2 = rounding 0,class:^(PacketTracer)$
#windowrulev2 = decorate 0,class:^(PacketTracer)$
#windowrulev2 = nearestneighbor on,class:^(PacketTracer)$ # force nearest neighbor scaling

### Behaviour ###
windowrulev2 = immediate on,class:^(PacketTracer)$ # force allow tearing
windowrulev2 = float,class:^(PacketTracer)$,title:negative:^(Cisco Packet Tracer)$
windowrulev2 = stayfocused,class:^(PacketTracer)$,title:negative:^(Cisco Packet Tracer)$ # Required for module dragging
#windowrulev2 = xray on,class:^(PacketTracer)$
#windowrulev2 = keepaspectratio on,title:^(Cisco Packet Tracer)$,class:^(PacketTracer)$
#windowrulev2 = focusonactivate on, title:^(Cisco Packet Tracer)$, class:^(PacketTracer)$

# Prevent the activity window from stealing the focus every 2 fucking seconds
windowrulev2 = suppressevent activate, title:^(PT Activity.*)$, class:PacketTracer
windowrulev2 = suppressevent activatefocus, title:^(PT Activity.*)$, class:PacketTracer
windowrulev2 = focusonactivate off, title:^(PT Activity.*), class:PacketTracer

### Sizing ###
windowrulev2 = minsize 1 1,class:^(PacketTracer)$
windowrulev2 = minsize 486 628,title:^(Preference)$,class:^(PacketTracer)$
windowrulev2 = minsize 486 628,title:^(.*outer.*)$,class:^(PacketTracer)$
windowrulev2 = minsize 772 700,title:^(.*witch.*)$,class:^(PacketTracer)$
windowrulev2 = minsize 807 655,title:^(.*PC.*)$,class:^(PacketTracer)$
windowrulev2 = minsize 791 648,title:^(.*Save File.*)$,class:^(PacketTracer)$
