# Picture-in-picture overlays
windowrule {
  name = pip
  match:title = ^Picture.+in.+[Pp]icture$

  float = true
  pin = true
  size = 600 338
  keep_aspect_ratio = true
  border_size = 0
  opacity = 1
  move = 100%-w-40 4%
}
#windowrulev2 = tag +pip, title:^(Picture.+in.+[Pp]icture)$
#windowrulev2 = float, tag:pip
#windowrulev2 = pin, tag:pip
#windowrulev2 = size 600 338, tag:pip
#windowrulev2 = keepaspectratio, tag:pip
#windowrulev2 = noborder, tag:pip
#windowrulev2 = opacity 1 1, tag:pip
#windowrulev2 = move 100%-w-40 4%, tag:pip
