# Force various windows to not float
windowrulev2 = tile, class:^remarkable\.exe$, title:^reMarkable$ # The initial reMarkable window starts floating, ensure it gets pinned
windowrulev2 = float, class:^reMarkable\.exe$, title:^Screen Share$ # Want the screen share window to be floating

