# Disable animations for selection overlay for screenshots

# Broken? Removes all animations regardless
#windowrule {
#  name = screenshot-animation
#  match:namespace = ^selection$
#  no_anim = true
#}

# Remove 1px border around hyprshot screenshots
windowrule {
  name = screenshot-border
  match:class = ^com.gabm.satty$
  border_size = 0
}
