# https://forum.endeavouros.com/t/hyprland-how-i-fixed-disappearing-drop-down-menus/49095
windowrulev2 = stayfocused, title:^()$,class:^(spotify)$
windowrulev2 = minsize 1 1, title:^()$,class:^(spotify)$

