# https://forum.endeavouros.com/t/hyprland-how-i-fixed-disappearing-drop-down-menus/49095
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$
windowrulev2 = float, title:^(Steam Settings)$,class:^(steam)$

