# Floating windows
windowrule {
  name = floating-applications
  match:class = (blueberry.py|Impala|Wiremix|org.gnome.NautilusPreviewer|com.gabm.satty|Omarchy|About|TUI.float|org.gnome.Calculator|org.speedcrunch.speedcrunch)

  tag = +floating-window
}

windowrule {
  name = system-popups
  match:class = (org\.freedesktop\.impl\.portal\.desktop\.kde|xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus)
  match:title = ^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*).*

  tag = +floating-window
}

windowrule {
  name = floating-window-tag
  match:tag = floating-window

  float = true
  center = true
  size = 800 600
}

windowrule {
  name = screensaver
  match:class = Screensaver

  fullscreen = true
}

windowrule {
  name = no-media-window-transparency
  match:class = ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$

  opacity = 1 1
}

