windowrule {
  name = virt_manager_connection_details
  match:class = virt-manager
  match:title = ^.*Connection Details$

  float = true
}

#windowrulev2 = float, class:^virt-manager$, title:^QEMU/KVM - Connection Details$
