# vi: ft=sshconfig

Host github.com
  AddKeysToAgent yes
  User git
  IdentityFile ~/.ssh/keys/github

Host gitlab.com
  AddKeysToAgent yes
  User git
  IdentityFile ~/.ssh/keys/gitlab

Host aur.archlinux.org
  AddKeysToAgent yes
  User aur
  IdentityFile ~/.ssh/keys/aur

Host codeberg.org
  AddKeysToAgent yes
  User git
  IdentityFile ~/.ssh/keys/codeberg
